#!/usr/bin/env python3

import os
import sys

# Setup some paths based on the directory that this script was run frum.
root_dir = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))

# Add the library directory to the LD_LIBRARY_PATH environement variable.
lib_dir = os.path.join(root_dir, "lib")
# Add the bin directory to PATH
bin_dir = os.path.join(root_dir, "bin")
if 'LD_LIBRARY_PATH' not in os.environ:
    os.environ['LD_LIBRARY_PATH'] = lib_dir
else:
    os.environ['LD_LIBRARY_PATH'] += ":" + lib_dir
os.environ['PATH'] += ":" + bin_dir
if 'RE_EXECED' not in os.environ:
    try:
        os.environ['RE_EXECED'] = "1"
        os.execv(sys.argv[0], sys.argv)
    except Exception as exc:
        print('Failed re-exec:', exc)
        sys.exit(1)

# Add the python directory to the python path
python_dir = os.path.join(root_dir, "lib/python" + str(sys.version_info.major) + \
                          "." + str(sys.version_info.minor) + "/site-packages")
sys.path.append(python_dir)

import io
import time
import queue
import argparse
import signal
import logging
import logging.handlers
import configparser
import multiprocessing as mp

from openhd import camera, telemetry, settings, video_player

# Define an exit handler to do a graceful shutdown
def exit_handler(sig, frame):
    sys.exit()

if __name__ == '__main__':

    # This program normally gets it's configuration from it's own config file,
    # but a second, OpenHD config file can also be used to update the setting
    # and also update the setting of the other OpenHD components.
    #
    # The first argument should be the component config file.
    # An option second argument is the OpenHD config file
    if len(sys.argv) != 2 and len(sys.argv) != 3:
        sys.stderr.write("Usage: " + sys.argv[0] + " <config file> [Open.HD config file]\n")
        exit(1)
    config_filename = sys.argv[1]

    # Read the config file
    config = configparser.ConfigParser()
    config['global'] = {
        'loglevel': 'error',
        'primary_camera': True,
        'video_port': 5600,
        'video_width': 10000,
        'video_height': 10000,
        'fps': 60,
        'bitrate': 3000000,
        'quality': 20,
        'inline_headers': True,
        'intra_period': 5,
        'prefer_picam': True,
        'secondary_camera': False,
        'video_port_secondary': 5601,
        'video_width_secondary': 10000,
        'video_height_secondary': 10000,
        'fps_secondary': 60,
        'bitrate_secondary': 3000000,
        'quality_secondary': 20,
        'inline_headers_secondary': True,
        'intra_period_secondary': 5,
        'prefer_picam_secondary': True,
        'fec_ratio_secondary': 0,
        'telemetry_uart': '/dev/ttyS0',
        'telemetry_baudrate': 115200,
        'rc_host': '127.0.0.1',
        'rc_port': 15441,
        'telemetry_protocol': 'mavlink',
        'telemetry_host': '127.0.0.1',
        'telemetry_port': 14550,
        'telemetry_uart': '/dev/ttyS0'
    }
    try:
        config.read(config_filename)
    except:
        print("Error reading the configuration file: " + config_filename)
        exit

    # Configure the logger
    log_level = getattr(logging, config['global'].get('loglevel').upper())
    if not isinstance(log_level, int):
        print("Invalid log level: %s - setting to info" % (args.loglevel))
        log_level = logging.INFO
    logger = logging.getLogger('openhd_controller')
    logging.basicConfig(level=log_level, format="%(asctime)s %(levelname)s: %(message)s", datefmt="%H:%M:%S",
                        handlers = [logging.StreamHandler(), logging.handlers.SysLogHandler(address = "/dev/log")])
    logging.info("Logging at level: " + config['global'].get('loglevel'))

    # Determine if we're running as ground or air by detecting if a camera is present
    cameras = camera.detect_cameras()
    if len(cameras) > 0:
        is_ground = False
        logging.info("At least one camera detected, so running in Air mode")
    else:
        is_ground = True
        logging.info("No camera detected, so running in Ground mode")

    # Parse the Open.HD config file if it exists.
    if len(sys.argv) == 3:
        if os.path.exists(sys.argv[2]):
            if is_ground:
                logging.info("Updating settings as ground from: " + sys.argv[2])
            else:
                logging.info("Updating settings as air from: " + sys.argv[2])
            sf = settings.Settings(sys.argv[2]) 
            sf.update(is_ground)

            # Reload our configuration file
            config.read(config_filename)

        else:
            logging.info("Open.HD settings file: " + sys.argv[2] + " does not exist")

        
    # Setup an exit handler to gracefully exit
    signal.signal(signal.SIGINT, exit_handler)

    # Start the camera process(es) if we're the air side
    cam = None
    cam2 = None
    if not is_ground:

        # Determine the primary camera device
        primary_camera = config['global'].get('primary_camera')
        primary_camera_index = -1
        if primary_camera is not False:
            if primary_camera == True or primary_camera == "True":
                primary_camera_index = 0
            else:
                for i, camer in enumerate(cameras):
                    if camer[0]['device'] == primary_camera:
                        primary_camera_index = i

        # Determine the secondary camera device
        secondary_camera = config['global'].get('secondary_camera')
        secondary_camera_index = -1
        if secondary_camera is not False:
            if secondary_camera == True or secondary_camera == "True":
                for i, camer in enumerate(cameras):
                    if i != primary_camera_index:
                        secondary_camera_index = i
                        break
            else:
                for i, camer in enumerate(cameras):
                    if camer[0]['device'] == secondary_camera:
                        secondary_camera_index = i

        # Create the primary camera process if we found a device to use
        if primary_camera_index >= 0:
            cam = camera.CameraProcess(device=cameras[primary_camera_index][0]['device'],
                                       width=int(config['global'].get('video_width')),
                                       height=int(config['global'].get('video_height')),
                                       fps=int(config['global'].get('fps')),
                                       bitrate=int(config['global'].get('bitrate')),
                                       quality=int(config['global'].get('quality')),
                                       inline_headers=bool(config['global'].get('inline_headers')),
                                       intra_period=int(config['global'].get('intra_period')),
                                       prefer_picam=bool(config['global'].get('prefer_picam')),
                                       fec_ratio=float(config['global'].get('fec_ratio')),
                                       port=int(config['global'].get('video_port')))
            logging.info("Using %s as primary camera",
                         (cameras[primary_camera_index][0]['device']))
            cam.start()

        # Start a secondary camera process?
        if secondary_camera_index >= 0:
            cam2 = camera.CameraProcess(device=cameras[secondary_camera_index][0]['device'],
                                        width=int(config['global'].get('video_width_secondary')),
                                        height=int(config['global'].get('video_height_secondary')),
                                        fps=int(config['global'].get('fps_secondary')),
                                        bitrate=int(config['global'].get('bitrate_secondary')),
                                        quality=int(config['global'].get('quality_secondary')),
                                        inline_headers=bool(config['global'].get('inline_headers_secondary')),
                                        intra_period=int(config['global'].get('intra_period_secondary')),
                                        prefer_picam=bool(config['global'].get('prefer_picam_secondary')),
                                        fec_ratio=float(config['global'].get('fec_ratio_secondary')),
                                        port=int(config['global'].get('video_port_secondary')))
            logging.info("Using %s as secondary camera",
                         (cameras[secondary_camera_index][0]['device']))
            cam2.start()

    # Start the telemetry parsers / forwarders
    if not is_ground:
        telem = telemetry.Telemetry(protocol=config['global'].get('telemetry_protocol'),
                                    uart=config['global'].get('telemetry_uart'),
                                    baudrate=config['global'].get('telemetry_baudrate'),
                                    host=config['global'].get('telemetry_host'),
                                    port=int(config['global'].get('telemetry_port')))
    else:
        telem = None

    # Start the video/osd player if ground
    if is_ground:
        video = video_player.VideoPlayer()
        if not video.running():
            video = None
    else:
        video = None

    # Wait for the processing threads to exit
    if is_ground:
        logging.info("Running in Ground mode")
    else:
        logging.info("Running in Air mode")
    if telem:
        telem.join()
    if cam:
        cam.join()
    if cam2:
        cam2.join()
    if video:
        video.join()
    if not telem and not cam and not video:
        while 1:
            time.sleep(1)

